version: "3.8"
services:
  mongodb:
      image : mongo
      container_name: mongodb
      restart: always
      build:
        context: .
        dockerfile: mongodb-data/Dockerfile    
      ports:
      - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: usr_test
        MONGO_INITDB_ROOT_PASSWORD: tanner    
      command: ['--auth']
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sql
    build:
      context: .
      dockerfile: sql-data/Dockerfile    
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "Password123"
        ACCEPT_EULA: "Y"
  # web-api:
  #   build: .
  #   container_name: template-webapi
  #   ports: 
  #     - "8081:80"      
  #   depends_on: 
  #     - sqlserver
  #     - mongodb   